version: '3'
services:
  backend:
    image: duelhunter/sps-backend:latest
    container_name: backend
    ports:
      - "5000:8080"
  
  frontend:
    image: duelhunter/sps-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend