version: '3'
services:
  backend:
    image: duelhunter/sps-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
  
  frontend:
    image: duelhunter/sps-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend